name: gcc
on: [push, pull_request, workflow_dispatch]
env:
  CI_DEPLOY_NEED_GCC: 1
  CI_DEPLOY_NEED_GRADLE: 1
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_MODULE: .
jobs:
  linux-ppc64le:
    runs-on: ubuntu-16.04
    container: ubuntu:focal
    steps:
      - uses: supergrecko/gcc/.github/actions/deploy-focal@master
  linux-x86_64:
    runs-on: ubuntu-16.04
    container: centos:6
    steps:
      - uses: supergrecko/javacpp-linux-environments/x86_64@staging
        with:
          needs_gcc: true
          github_respository: ${{ env.GITHUB_REPOSITORY }}
          github_hash: ${{ env.GITHUB_HASH }}
          build_system: gradle
  redeploy:
    needs: [linux-ppc64le, linux-x86_64]
    runs-on: ubuntu-16.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@master